# Generated by Django 5.2.2 on 2025-06-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
